# -*- coding: utf-8 -*-
"""dsip9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FLI6_N0me5mgV84Jda4LJYxUVbTwpNd
"""

#write a python program to simulate smoothening and sharpening operation on image using spatial filter
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
# Load the image
image = cv2.imread('/content/image1.jpg')

# Define the Gaussian kernel for smoothing
kernel_size = (5, 5)
sigma = 1.5
gaussian_kernel = cv2.getGaussianKernel(kernel_size[0], sigma)
gaussian_kernel = np.outer(gaussian_kernel, gaussian_kernel)


# Apply Gaussian smoothing
smoothed_image = cv2.filter2D(image, -1, gaussian_kernel)


# Define a sharpening kernel
sharpening_kernel = np.array([[-1, -1, -1],
                              [-1, 9, -1],
                              [-1, -1, -1]])

# Apply sharpening
sharpened_image = cv2.filter2D(image, -1, sharpening_kernel)
# Display the original image, smoothed, and sharpened images
cv2_imshow(image)
cv2_imshow(smoothed_image)
cv2_imshow(sharpened_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Define averaging filter size
kernel_size = (5, 5)

# Create averaging filter
kernel = np.ones(kernel_size, dtype=np.float32) / 25

# Apply averaging filter
smoothed_image = cv2.filter2D(image, -1, kernel)

# Display images
print("Original Image")
cv2_imshow(image)
print("Averaging Filter Smoothed Image")
cv2_imshow(smoothed_image)

# Define median filter size
kernel_size = 5

# Apply median filter
smoothed_image = cv2.medianBlur(image, kernel_size)

# Display images
print("Original Image")
cv2_imshow(image)

print("Median Filter Smoothed Image")
cv2_imshow(smoothed_image)